-- THE SEASON V3 — Supabase schema, no login
create table if not exists public.teams(
 id bigint generated by default as identity primary key,
 class_name text not null, name text not null, sort_order int not null default 0,
 active boolean not null default true, unique(class_name,name)
);
create table if not exists public.teachers(
 id bigint generated by default as identity primary key,
 name text not null unique, active boolean not null default true
);
create table if not exists public.lessons(
 id bigint generated by default as identity primary key,
 lesson_date date not null, class_name text not null, title text,
 teaching_team_id bigint references public.teams(id) on delete set null
);
create table if not exists public.criteria(
 id bigint generated by default as identity primary key,
 name text not null unique, short_name text,
 applies_to text not null default 'all' check(applies_to in('all','teaching')),
 min_points int not null default 0,max_points int not null default 3,
 sort_order int not null default 0,active boolean not null default true,
 check(max_points>=min_points)
);
create table if not exists public.scores(
 id bigint generated by default as identity primary key,
 lesson_id bigint not null references public.lessons(id) on delete cascade,
 team_id bigint not null references public.teams(id) on delete cascade,
 criterion_id bigint not null references public.criteria(id) on delete cascade,
 teacher_id bigint references public.teachers(id) on delete set null,
 points int not null,created_at timestamptz not null default now(),
 unique(lesson_id,team_id,criterion_id)
);

alter table public.teams enable row level security;
alter table public.teachers enable row level security;
alter table public.lessons enable row level security;
alter table public.criteria enable row level security;
alter table public.scores enable row level security;

create policy "anon read teams" on public.teams for select to anon using(true);
create policy "anon read teachers" on public.teachers for select to anon using(true);
create policy "anon read lessons" on public.lessons for select to anon using(true);
create policy "anon read criteria" on public.criteria for select to anon using(true);
create policy "anon read scores" on public.scores for select to anon using(true);

create policy "anon teams crud" on public.teams for all to anon using(true) with check(true);
create policy "anon teachers crud" on public.teachers for all to anon using(true) with check(true);
create policy "anon lessons crud" on public.lessons for all to anon using(true) with check(true);
create policy "anon criteria crud" on public.criteria for all to anon using(true) with check(true);
create policy "anon scores crud" on public.scores for all to anon using(true) with check(true);

insert into public.criteria(name,short_name,applies_to,min_points,max_points,sort_order) values
('Klaar?','Klaar','all',0,3,1),
('Inzet','Inzet','all',0,3,2),
('Doelen bereikt?','Doelen','teaching',0,3,3)
on conflict(name) do nothing;

insert into public.teachers(name) values ('Tom'),('Jan'),('Sofie'),('Michael') on conflict(name) do nothing;

insert into public.teams(class_name,name,sort_order) values
('3LOA','Groep 1',1),('3LOA','Groep 2',2),('3LOA','Groep 3',3),('3LOA','Groep 4',4),
('3LOB','Groep 1',1),('3LOB','Groep 2',2),('3LOB','Groep 3',3),('3LOB','Groep 4',4),
('3LOC','Groep 1',1),('3LOC','Groep 2',2),('3LOC','Groep 3',3),('3LOC','Groep 4',4)
on conflict(class_name,name) do nothing;


-- V5 junction tables
create table if not exists public.lesson_evaluators(
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  primary key (lesson_id, teacher_id)
);
create table if not exists public.lesson_criteria(
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  criterion_id bigint not null references public.criteria(id) on delete cascade,
  primary key (lesson_id, criterion_id)
);
alter table public.lesson_evaluators enable row level security;
alter table public.lesson_criteria enable row level security;
create policy "anon lesson evaluators crud" on public.lesson_evaluators for all to anon using(true) with check(true);
create policy "anon lesson criteria crud" on public.lesson_criteria for all to anon using(true) with check(true);
grant select, insert, update, delete on table public.lesson_evaluators to anon;
grant select, insert, update, delete on table public.lesson_criteria to anon;
